FROM openjdk:17-jdk-slim
WORKDIR /app
COPY OnlineJobPortal1122-0.0.1-SNAPSHOT.jar OnlineJobPortal1122-0.0.1-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "OnlineJobPortal1122-0.0.1-SNAPSHOT.jar"]
